spring:
  application:
    name: taco-cloud
  h2:
    console:
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:tacocloud
    driver-class-name: org.h2.Driver
    generate-unique-name: false
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

#server:
#  port: 8088
#spring:
#  data:
#    mongodb:
#      username: admin
#      password: password
#      host: localhost
#      port: 27017
#      database: tacoclouddb
#      authentication-database: admin
